// Export all custom icons
export { WaterDropletIcon, WaterDropletFilledIcon } from './WaterDropletIcon'
export { default as BloodDropIcon } from './BloodDropIcon'

// Export all Heroicons replacements
export { MagnifyingGlassIcon } from './MagnifyingGlassIcon'
export { MapPinIcon } from './MapPinIcon'
export { BeakerIcon } from './BeakerIcon'
export { BuildingOfficeIcon } from './BuildingOfficeIcon'
export { PhoneIcon } from './PhoneIcon'
export { ExclamationTriangleIcon } from './ExclamationTriangleIcon'
export { ClockIcon } from './ClockIcon'
export { EnvelopeIcon } from './EnvelopeIcon'
export { PaperAirplaneIcon } from './PaperAirplaneIcon'
export { CheckCircleIcon } from './CheckCircleIcon'
export { XCircleIcon } from './XCircleIcon'
export { FunnelIcon } from './FunnelIcon'
export { CalendarIcon } from './CalendarIcon'
export { ChartBarIcon } from './ChartBarIcon'
export { UsersIcon } from './UsersIcon'
export { BellIcon } from './BellIcon'
export { PlusIcon } from './PlusIcon'
export { LockClosedIcon } from './LockClosedIcon'
export { EyeIcon } from './EyeIcon'
export { EyeSlashIcon } from './EyeSlashIcon'
export { UserIcon } from './UserIcon'
export { HeartIcon } from './HeartIcon'
export { ShieldCheckIcon } from './ShieldCheckIcon'
export { AcademicCapIcon } from './AcademicCapIcon'
export { GlobeAltIcon } from './GlobeAltIcon'
export { UserGroupIcon } from './UserGroupIcon'
export { ArrowRightOnRectangleIcon } from './ArrowRightOnRectangleIcon'
export { InformationCircleIcon } from './InformationCircleIcon'
export { Bars3Icon } from './Bars3Icon'
export { XMarkIcon } from './XMarkIcon'
export { UserCircleIcon } from './UserCircleIcon'
export { ExclamationCircleIcon } from './ExclamationCircleIcon'
export { WaterDropIcon } from './WaterDropIcon'